### ISSUE TITLE
Transfer repository to `bazel-contrib`

### ISSUE THREAD

**Issue by cgrindel** [bazel-contrib/rules_bazel_integration_test#47]
## Tasks

- [x] Transfer the repository
- [x] Update references in workspace snippet and doc to new URL: 
  - [x] #48 
  - [x] #51
- [x] Set up the release process
- [x] #57
- [x] Generate a release. ([v0.6.2](https://github.com/bazel-contrib/rules_bazel_integration_test/releases/tag/v0.6.2))
- [x] Update references in other repos
  - [x] [cgrindel/bazel-starlib](https://github.com/cgrindel/bazel-starlib): cgrindel/bazel-starlib#139
  - [x] [keith/buildifier-prebuilt](https://github.com/keith/buildifier-prebuilt): keith/buildifier-prebuilt#30
  - [x] [buildbuddy-io/rules_xcodeproj](https://github.com/buildbuddy-io/rules_xcodeproj): buildbuddy-io/rules_xcodeproj#302
  - [x] [cgrindel/rules_swiftformat](https://github.com/cgrindel/rules_swiftformat): cgrindel/rules_swiftformat#55
  - [x] [cgrindel/rules_spm](https://github.com/cgrindel/rules_spm): cgrindel/rules_spm#137
- [ ] Send announcement on Slack and ???
